media: 
  input: public/static
  output: /static
content:
  - name: funny
    label: Funny
    type: collection
    path: app/content/funny
    view: 
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Publish Date, type: date, options: { time: true, format: dd-MM-yyyy HH:mm } }
      - { name: body, label: Body, type: text }
      - { name: img1, label: Image, type: image }
      - { name: img2, label: Image, type: image }
  - name: news
    label: News
    type: collection
    path: app/content/news
    view: 
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Publish Date, type: date, options: { time: true, format: dd-MM-yyyy HH:mm } }
      - { name: news1, label: Body, type: text }
      - { name: img1, label: Image, type: image }
      - { name: img2, label: Image, type: image }
      - { name: news2, label: Body, type: text }
      - { name: news3, label: Body, type: text }
      - { name: img3, label: Image, type: image }
      - { name: img4, label: Image, type: image }
      - { name: news4, label: Body, type: text }
      - { name: news5, label: Body, type: text }
      - { name: img5, label: Image, type: image }